// Web Push opt-in for the PWA. The service worker (generated by vite-plugin-pwa,
// with push handlers layered in via priv/static/push-sw.js) shows the
// notification; this module manages the browser subscription and mirrors it to
// the server so `suikou review notify` can reach it.
//
// Push only runs in a secure context — HTTPS or localhost. Over the tailnet that
// means the app must be fronted with HTTPS (tailscale serve); on plain HTTP the
// browser exposes no PushManager and `supported()` is false.

const SUBSCRIBE_URL = "/api/push/subscribe"
const CONFIG_URL = "/api/push/config"

type PushConfig = { public_key: string }

// The push config is immutable for the server's lifetime (it comes from boot-time
// config), so fetch it once and share the promise between the settings panel and
// the subscribe flow rather than hitting the endpoint twice.
let configPromise: Promise<PushConfig> | null = null

function pushConfig(): Promise<PushConfig> {
  configPromise ??= fetch(CONFIG_URL)
    .then((response) => response.json() as Promise<PushConfig>)
    .catch((error) => {
      // Don't cache a failure — the next caller should retry.
      configPromise = null
      throw error
    })
  return configPromise
}

/** Whether this browser can subscribe at all: secure context + the push APIs. */
export function supported(): boolean {
  return (
    typeof window !== "undefined" &&
    window.isSecureContext &&
    "serviceWorker" in navigator &&
    "PushManager" in window &&
    "Notification" in window
  )
}

/** Why the toggle is unavailable, or null when it can be used. */
export function unavailableReason(): "unsupported" | "denied" | null {
  if (!supported()) return "unsupported"
  if (Notification.permission === "denied") return "denied"
  return null
}

/** Whether a push subscription currently exists for this browser. Never throws. */
export async function isSubscribed(): Promise<boolean> {
  if (!supported()) return false
  try {
    const registration = await navigator.serviceWorker.getRegistration()
    if (!registration) return false
    return (await registration.pushManager.getSubscription()) !== null
  } catch {
    return false
  }
}

/** Requests permission, subscribes, and registers the subscription server-side.
 * Returns false — the enabled state to reflect — if unsupported, permission was
 * refused, no SW is registered (e.g. the dev server, which ships none), or the
 * network registration failed. Never throws, so the toggle can await it plainly. */
export async function enable(): Promise<boolean> {
  if (!supported()) return false
  try {
    if ((await Notification.requestPermission()) !== "granted") return false

    const registration = await navigator.serviceWorker.getRegistration()
    if (!registration) return false

    const subscription =
      (await registration.pushManager.getSubscription()) ??
      (await registration.pushManager.subscribe({
        userVisibleOnly: true,
        applicationServerKey: await fetchVapidKey(),
      }))

    const keys = subscription.toJSON().keys ?? {}
    const response = await fetch(SUBSCRIBE_URL, {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({ endpoint: subscription.endpoint, p256dh: keys.p256dh, auth: keys.auth }),
    })
    return response.ok
  } catch {
    return false
  }
}

/** Drops the subscription in the browser, then best-effort on the server. Never
 * throws; a failed server delete self-heals — the next push prunes it on 410. */
export async function disable(): Promise<void> {
  try {
    const registration = await navigator.serviceWorker.getRegistration()
    const subscription = registration && (await registration.pushManager.getSubscription())
    if (!subscription) return

    const endpoint = subscription.endpoint
    await subscription.unsubscribe()
    await fetch(SUBSCRIBE_URL, {
      method: "DELETE",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({ endpoint }),
    })
  } catch {
    // best-effort — browser unsubscribe is what matters; the server row expires.
  }
}

async function fetchVapidKey(): Promise<Uint8Array<ArrayBuffer>> {
  return urlBase64ToUint8Array((await pushConfig()).public_key)
}

// The VAPID key arrives base64url; PushManager wants the raw bytes.
function urlBase64ToUint8Array(base64url: string): Uint8Array<ArrayBuffer> {
  const padding = "=".repeat((4 - (base64url.length % 4)) % 4)
  const base64 = (base64url + padding).replace(/-/g, "+").replace(/_/g, "/")
  const raw = atob(base64)
  const bytes = new Uint8Array(raw.length)
  for (let i = 0; i < raw.length; i++) bytes[i] = raw.charCodeAt(i)
  return bytes
}
